---
- name: link shared dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/.dotfiles/bash_profile", dest: "~/.bash_profile"}
    - { src: "~/.dotfiles/bashrc", dest: "~/.bashrc"}
    - { src: "~/.dotfiles/gitconfig", dest: "~/.gitconfig"}
    - { src: "~/.dotfiles/tmux.conf", dest: "~/.tmux.conf"}
    - { src: "~/.dotfiles/vimrc", dest: "~/.vimrc"}
    - { src: "~/.dotfiles/vimrc", dest: "~/.ideavimrc"}
    - { src: "~/.dotfiles/vimrc", dest: "~/.config/nvim/init.vim"}
    - { src: "~/.dotfiles/plugins.toml", dest: "~/.config/dein/plugins.toml"}
    - { src: "~/.dotfiles/starship.toml", dest: "~/.config/starship.toml"}
