---
- name: Playbook to manage nakabonne dotfiles (https://github.com/nakabonne/dotfiles-ansible)
  hosts: localhost
  connection: local
  tasks:
    - name: load custom vars
      include_vars: ../vars.yml
      tags:
        - always

    - name: Allow sudo without password
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: "{{ ansible_user_id }}	ALL=NOPASSWD: ALL"
        insertafter:  '^%admin\tALL=\(ALL\) ALL'
        validate: "visudo -cf %s"
      become: yes
      when: sudo_without_password and ansible_os_family == "Darwin"

    - name: Create folder
      file:
        path: "{{item}}"
        state: directory
      loop:
        - "~/.config/nvim/"
        - "~/.config/dein/"

    - include: tasks/link_files.yml
      tags:
        - links

    - include: tasks/docker.yml
      tags:
        - docker

    # Install via packages
    - include: tasks/packages.yml
      tags:
        - packages

    # Install via Git
    - name: Install pyenv
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: ~/.pyenv
        update: yes

    - name: Install anyenv
      git:
        repo: https://github.com/anyenv/anyenv
        dest: ~/.anyenv
        update: yes

    - name: Install enhancd
      git:
        repo: https://github.com/b4b4r07/enhancd
        dest: ~/.enhancd
        update: yes

    - name: Download fzf
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf
        update: yes
        depth: 1
    - name: Install fzf
      shell:
        cmd: ~/.fzf/install --all

    - name: Download starship
      uri:
        url: https://starship.rs/install.sh
        return_content: yes
      register: starship_installer
    - name: Install starship
      shell:
        cmd: sh -s -- -y
        stdin: "{{ starship_installer.content }}"

    # FIXME: Install dein
    # See: https://github.com/Shougo/dein.vim#quick-start
    # - name: Download dein
    #   uri:
    #     url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
    #     return_content: yes
    #     dest: ~/dein_installer.sh
    # - name: Install dein
    #   shell:
    #     cmd: sh ~/dein_installer.sh ~/.config/nvim

    # FIXME: Install neovim via PPA
    # See: https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu

    # FIXME: Install via curl
    # - https://github.com/monochromegane/the_platinum_searcher
    # - https://github.com/x-motemen/ghq

    - include: tasks/ubuntu.yml
      when: ansible_os_family == "Debian"
      tags:
        - ubuntu

    - include: tasks/macos.yml
      when: ansible_os_family == "Darwin"
      tags:
        - macos

